AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gcs-s3-sync


Globals:
  Function:
    Timeout: 30

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: yokobot-dev #TODO　環境変数から取得するように修正する

  GcsS3SyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        GcsS3Sync:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*

Outputs:
  GcsS3SyncFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt GcsS3SyncFunction.Arn
  GcsS3SyncFunctionIamRole:
    Description: "Implicit IAM Role created for lambda function"
    Value: !GetAtt GcsS3SyncFunctionRole.Arn
